// Code generated by goctl. DO NOT EDIT.
// Source: sys.proto

package departmentservice

import (
	"context"

	"code-storm/rpc/sys/sysClient"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddAppReq            = sysClient.AddAppReq
	AddAppResp           = sysClient.AddAppResp
	AddDepartmentReq     = sysClient.AddDepartmentReq
	AddDepartmentResp    = sysClient.AddDepartmentResp
	AddPermissionReq     = sysClient.AddPermissionReq
	AddPermissionResp    = sysClient.AddPermissionResp
	AddRoleReq           = sysClient.AddRoleReq
	AddRoleResp          = sysClient.AddRoleResp
	AppInfoReq           = sysClient.AppInfoReq
	AppInfoResp          = sysClient.AppInfoResp
	DeleteAppReq         = sysClient.DeleteAppReq
	DeleteAppResp        = sysClient.DeleteAppResp
	DeleteDepartmentReq  = sysClient.DeleteDepartmentReq
	DeleteDepartmentResp = sysClient.DeleteDepartmentResp
	DeletePermissionReq  = sysClient.DeletePermissionReq
	DeletePermissionResp = sysClient.DeletePermissionResp
	DeleteRoleReq        = sysClient.DeleteRoleReq
	DeleteRoleResp       = sysClient.DeleteRoleResp
	DepartmentInfoReq    = sysClient.DepartmentInfoReq
	DepartmentInfoResp   = sysClient.DepartmentInfoResp
	ListAppReq           = sysClient.ListAppReq
	ListAppResp          = sysClient.ListAppResp
	ListDepartmentReq    = sysClient.ListDepartmentReq
	ListDepartmentResp   = sysClient.ListDepartmentResp
	ListPermissionReq    = sysClient.ListPermissionReq
	ListPermissionResp   = sysClient.ListPermissionResp
	ListRoleReq          = sysClient.ListRoleReq
	ListRoleResp         = sysClient.ListRoleResp
	LoginReq             = sysClient.LoginReq
	LoginResp            = sysClient.LoginResp
	PermissionInfoReq    = sysClient.PermissionInfoReq
	PermissionInfoResp   = sysClient.PermissionInfoResp
	RoleInfoReq          = sysClient.RoleInfoReq
	RoleInfoResp         = sysClient.RoleInfoResp
	UpdateAppReq         = sysClient.UpdateAppReq
	UpdateAppResp        = sysClient.UpdateAppResp
	UpdateDepartmentReq  = sysClient.UpdateDepartmentReq
	UpdateDepartmentResp = sysClient.UpdateDepartmentResp
	UpdatePermissionReq  = sysClient.UpdatePermissionReq
	UpdatePermissionResp = sysClient.UpdatePermissionResp
	UpdateRoleReq        = sysClient.UpdateRoleReq
	UpdateRoleResp       = sysClient.UpdateRoleResp
	UserInfo             = sysClient.UserInfo
	UserListReq          = sysClient.UserListReq
	UserListResp         = sysClient.UserListResp

	DepartmentService interface {
		DepartmentAdd(ctx context.Context, in *AddDepartmentReq, opts ...grpc.CallOption) (*AddDepartmentResp, error)
		DepartmentInfo(ctx context.Context, in *DepartmentInfoReq, opts ...grpc.CallOption) (*DepartmentInfoResp, error)
		DepartmentList(ctx context.Context, in *ListDepartmentReq, opts ...grpc.CallOption) (*ListDepartmentResp, error)
		DepartmentUpdate(ctx context.Context, in *UpdateDepartmentReq, opts ...grpc.CallOption) (*UpdateDepartmentResp, error)
		DepartmentDelete(ctx context.Context, in *DeleteDepartmentReq, opts ...grpc.CallOption) (*DeleteDepartmentResp, error)
	}

	defaultDepartmentService struct {
		cli zrpc.Client
	}
)

func NewDepartmentService(cli zrpc.Client) DepartmentService {
	return &defaultDepartmentService{
		cli: cli,
	}
}

func (m *defaultDepartmentService) DepartmentAdd(ctx context.Context, in *AddDepartmentReq, opts ...grpc.CallOption) (*AddDepartmentResp, error) {
	client := sysClient.NewDepartmentServiceClient(m.cli.Conn())
	return client.DepartmentAdd(ctx, in, opts...)
}

func (m *defaultDepartmentService) DepartmentInfo(ctx context.Context, in *DepartmentInfoReq, opts ...grpc.CallOption) (*DepartmentInfoResp, error) {
	client := sysClient.NewDepartmentServiceClient(m.cli.Conn())
	return client.DepartmentInfo(ctx, in, opts...)
}

func (m *defaultDepartmentService) DepartmentList(ctx context.Context, in *ListDepartmentReq, opts ...grpc.CallOption) (*ListDepartmentResp, error) {
	client := sysClient.NewDepartmentServiceClient(m.cli.Conn())
	return client.DepartmentList(ctx, in, opts...)
}

func (m *defaultDepartmentService) DepartmentUpdate(ctx context.Context, in *UpdateDepartmentReq, opts ...grpc.CallOption) (*UpdateDepartmentResp, error) {
	client := sysClient.NewDepartmentServiceClient(m.cli.Conn())
	return client.DepartmentUpdate(ctx, in, opts...)
}

func (m *defaultDepartmentService) DepartmentDelete(ctx context.Context, in *DeleteDepartmentReq, opts ...grpc.CallOption) (*DeleteDepartmentResp, error) {
	client := sysClient.NewDepartmentServiceClient(m.cli.Conn())
	return client.DepartmentDelete(ctx, in, opts...)
}
