// Code generated by goctl. DO NOT EDIT.
// Source: sys.proto

package server

import (
	"context"

	"code-storm/rpc/sys/internal/logic/roleservice"
	"code-storm/rpc/sys/internal/svc"
	"code-storm/rpc/sys/sysClient"
)

type RoleServiceServer struct {
	svcCtx *svc.ServiceContext
	sysClient.UnimplementedRoleServiceServer
}

func NewRoleServiceServer(svcCtx *svc.ServiceContext) *RoleServiceServer {
	return &RoleServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *RoleServiceServer) RoleAdd(ctx context.Context, in *sysClient.AddRoleReq) (*sysClient.AddRoleResp, error) {
	l := roleservicelogic.NewRoleAddLogic(ctx, s.svcCtx)
	return l.RoleAdd(in)
}

func (s *RoleServiceServer) RoleInfo(ctx context.Context, in *sysClient.RoleInfoReq) (*sysClient.RoleInfoResp, error) {
	l := roleservicelogic.NewRoleInfoLogic(ctx, s.svcCtx)
	return l.RoleInfo(in)
}

func (s *RoleServiceServer) RoleList(ctx context.Context, in *sysClient.ListRoleReq) (*sysClient.ListRoleResp, error) {
	l := roleservicelogic.NewRoleListLogic(ctx, s.svcCtx)
	return l.RoleList(in)
}

func (s *RoleServiceServer) RoleUpdate(ctx context.Context, in *sysClient.UpdateRoleReq) (*sysClient.UpdateRoleResp, error) {
	l := roleservicelogic.NewRoleUpdateLogic(ctx, s.svcCtx)
	return l.RoleUpdate(in)
}

func (s *RoleServiceServer) RoleDelete(ctx context.Context, in *sysClient.DeleteRoleReq) (*sysClient.DeleteRoleResp, error) {
	l := roleservicelogic.NewRoleDeleteLogic(ctx, s.svcCtx)
	return l.RoleDelete(in)
}
