// Code generated by goctl. DO NOT EDIT.
// Source: sys.proto

package server

import (
	"context"

	"code-storm/rpc/sys/internal/logic/appservice"
	"code-storm/rpc/sys/internal/svc"
	"code-storm/rpc/sys/sysClient"
)

type AppServiceServer struct {
	svcCtx *svc.ServiceContext
	sysClient.UnimplementedAppServiceServer
}

func NewAppServiceServer(svcCtx *svc.ServiceContext) *AppServiceServer {
	return &AppServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *AppServiceServer) AppAdd(ctx context.Context, in *sysClient.AddAppReq) (*sysClient.AddAppResp, error) {
	l := appservicelogic.NewAppAddLogic(ctx, s.svcCtx)
	return l.AppAdd(in)
}

func (s *AppServiceServer) AppInfo(ctx context.Context, in *sysClient.AppInfoReq) (*sysClient.AppInfoResp, error) {
	l := appservicelogic.NewAppInfoLogic(ctx, s.svcCtx)
	return l.AppInfo(in)
}

func (s *AppServiceServer) AppList(ctx context.Context, in *sysClient.ListAppReq) (*sysClient.ListAppResp, error) {
	l := appservicelogic.NewAppListLogic(ctx, s.svcCtx)
	return l.AppList(in)
}

func (s *AppServiceServer) AppUpdate(ctx context.Context, in *sysClient.UpdateAppReq) (*sysClient.UpdateAppResp, error) {
	l := appservicelogic.NewAppUpdateLogic(ctx, s.svcCtx)
	return l.AppUpdate(in)
}

func (s *AppServiceServer) AppDelete(ctx context.Context, in *sysClient.DeleteAppReq) (*sysClient.DeleteAppResp, error) {
	l := appservicelogic.NewAppDeleteLogic(ctx, s.svcCtx)
	return l.AppDelete(in)
}
