// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"code-storm/rpc/user/internal/logic"
	"code-storm/rpc/user/internal/svc"
	"code-storm/rpc/user/userclient"
)

type UserServiceServer struct {
	svcCtx *svc.ServiceContext
	userclient.UnimplementedUserServiceServer
}

func NewUserServiceServer(svcCtx *svc.ServiceContext) *UserServiceServer {
	return &UserServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServiceServer) Login(ctx context.Context, in *userclient.LoginReq) (*userclient.LoginResp, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UserServiceServer) GetUserList(ctx context.Context, in *userclient.UserListReq) (*userclient.UserListResp, error) {
	l := logic.NewGetUserListLogic(ctx, s.svcCtx)
	return l.GetUserList(in)
}
