// Code generated by goctl. DO NOT EDIT.
package types

type AddAppReq struct {
	Name                  string `json:"name"`
	AppId                 string `json:"appId"`
	Key                   string `json:"key"`
	Secret                string `json:"secret"`
	GrantType             string `json:"grantType"`
	RedirectUri           string `json:"redirectUri"`
	AdditionalInformation string `json:"additionalInformation"`
	AccessTokenValidity   int64  `json:"accessTokenValidity"`
	RefreshTokenValidity  int64  `json:"refreshTokenValidity"`
}

type AddAppResp struct {
	Data string `json:"data"`
}

type AppData struct {
	Id                    string `json:"id"`
	Name                  string `json:"name"`
	AppId                 string `json:"appId"`
	Key                   string `json:"key"`
	Secret                string `json:"secret"`
	GrantType             string `json:"grantType"`
	RedirectUri           string `json:"redirectUri"`
	AdditionalInformation string `json:"additionalInformation"`
	AccessTokenValidity   int64  `json:"accessTokenValidity"`
	CreateAt              string `json:"createAt"`
	UpdateAt              string `json:"updateAt"`
	Status                int64  `json:"status"`
	CreateUser            string `json:"createUser"`
	UpdateUser            string `json:"updateUser"`
}

type AppInfoReq struct {
	Id string `json:"id"`
}

type DeleteAppReq struct {
	Ids []string `json:"ids"`
}

type DeleteAppResp struct {
	Data string `json:"data"`
}

type ListAppReq struct {
	Current  int64  `json:"current,default=1"`
	PageSize int64  `json:"pageSize,default=10"`
	Name     string `json:"name,optional"`
}

type ListAppResp struct {
	Data      []AppData `json:"data"`
	Current   int64     `json:"current"`
	PageSize  int64     `json:"pageSize"`
	Total     int64     `json:"total"`
	TotalPage int64     `json:"totalPage"`
}

type LoginRequest struct {
	AppId    string `json:"appId"`
	Account  string `json:"account"`
	Password string `json:"password"`
}

type LoginResp struct {
	Id           string `json:"id"`
	Account      string `json:"userName"`
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type UpdateAppReq struct {
	Id                    string `json:"id"`
	Name                  string `json:"name"`
	AppId                 string `json:"appId"`
	Key                   string `json:"key"`
	Secret                string `json:"secret"`
	GrantType             string `json:"grantType"`
	RedirectUri           string `json:"redirectUri"`
	AdditionalInformation string `json:"additionalInformation"`
	AccessTokenValidity   int64  `json:"accessTokenValidity"`
	Status                int64  `json:"status"`
}

type UpdateAppResp struct {
	Data string `json:"data"`
}
