// Code generated by goctl. DO NOT EDIT.
package types

type AddClientReq struct {
	Name           string `json:"name"`
	Remark         string `json:"remark"`
	ClientId       string `json:"clientId"`
	ClientSecret   string `json:"clientSecret"`
	ClientKey      string `json:"clientKey"`
	AdditionalInfo string `json:"additionalInfo"`
	GrantType      string `json:"grantType"`
	ExpireIn       int64  `json:"expireIn"`
	RefreshAfter   int64  `json:"refreshAfter"`
}

type AddClientResp struct {
	Data string `json:"data"`
}

type ClientData struct {
	Id             string `json:"id"`
	Name           string `json:"name"`
	Remark         string `json:"remark"`
	ClientId       string `json:"clientId"`
	ClientSecret   string `json:"clientSecret"`
	ClientKey      string `json:"clientKey"`
	AdditionalInfo string `json:"additionalInfo"`
	GrantType      string `json:"grantType"`
	ExpireIn       int64  `json:"expireIn"`
	RefreshAfter   int64  `json:"refreshAfter"`
	Status         int64  `json:"status"`
	IsDeleted      int64  `json:"isDeleted"`
}

type ClientInfoReq struct {
	Id string `json:"id"`
}

type DeleteClientReq struct {
	Id []string `json:"ids"`
}

type DeleteClientResp struct {
	Data string `json:"data"`
}

type ListClientReq struct {
	Current  int64  `json:"current,default=1"`
	PageSize int64  `json:"pageSize,default=10"`
	Name     string `json:"name,optional"`
}

type ListClientResp struct {
	Data      []ClientData `json:"data"`
	Current   int64        `json:"current"`
	PageSize  int64        `json:"pageSize"`
	Total     int64        `json:"total"`
	TotalPage int64        `json:"totalPage"`
}

type LoginRequest struct {
	Account  string `json:"account"`
	Password string `json:"password"`
}

type LoginResp struct {
	Id           string `json:"id"`
	Account      string `json:"userName"`
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type UpdateClientReq struct {
	Id     string `json:"id"`
	Name   string `json:"name"`
	Remark string `json:"remark"`
	Status int64  `json:"status"`
}

type UpdateClientResp struct {
	Data string `json:"data"`
}
