// Code generated by goctl. DO NOT EDIT.
package types

type LoginRequest struct {
	Username string
	Password string
}

type LoginResp struct {
	Status           string `json:"status"`
	CurrentAuthority string `json:"currentAuthority"`
	Id               int64  `json:"id"`
	UserName         string `json:"userName"`
	AccessToken      string `json:"token"`
	AccessExpire     int64  `json:"accessExpire"`
	RefreshAfter     int64  `json:"refreshAfter"`
}
