// Code generated by goctl. DO NOT EDIT.
// Source: sys.proto

package server

import (
	"context"

	"code-storm/rpc/sys/internal/logic/departmentservice"
	"code-storm/rpc/sys/internal/svc"
	"code-storm/rpc/sys/sysClient"
)

type DepartmentServiceServer struct {
	svcCtx *svc.ServiceContext
	sysClient.UnimplementedDepartmentServiceServer
}

func NewDepartmentServiceServer(svcCtx *svc.ServiceContext) *DepartmentServiceServer {
	return &DepartmentServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *DepartmentServiceServer) DepartmentAdd(ctx context.Context, in *sysClient.AddDepartmentReq) (*sysClient.AddDepartmentResp, error) {
	l := departmentservicelogic.NewDepartmentAddLogic(ctx, s.svcCtx)
	return l.DepartmentAdd(in)
}

func (s *DepartmentServiceServer) DepartmentInfo(ctx context.Context, in *sysClient.DepartmentInfoReq) (*sysClient.DepartmentInfoResp, error) {
	l := departmentservicelogic.NewDepartmentInfoLogic(ctx, s.svcCtx)
	return l.DepartmentInfo(in)
}

func (s *DepartmentServiceServer) DepartmentList(ctx context.Context, in *sysClient.ListDepartmentReq) (*sysClient.ListDepartmentResp, error) {
	l := departmentservicelogic.NewDepartmentListLogic(ctx, s.svcCtx)
	return l.DepartmentList(in)
}

func (s *DepartmentServiceServer) DepartmentUpdate(ctx context.Context, in *sysClient.UpdateDepartmentReq) (*sysClient.UpdateDepartmentResp, error) {
	l := departmentservicelogic.NewDepartmentUpdateLogic(ctx, s.svcCtx)
	return l.DepartmentUpdate(in)
}

func (s *DepartmentServiceServer) DepartmentDelete(ctx context.Context, in *sysClient.DeleteDepartmentReq) (*sysClient.DeleteDepartmentResp, error) {
	l := departmentservicelogic.NewDepartmentDeleteLogic(ctx, s.svcCtx)
	return l.DepartmentDelete(in)
}
