// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package client

import (
	"context"

	"code-storm/rpc/user/userclient"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	LoginReq  = userclient.LoginReq
	LoginResp = userclient.LoginResp

	UserService interface {
		Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
	}

	defaultUserService struct {
		cli zrpc.Client
	}
)

func NewUserService(cli zrpc.Client) UserService {
	return &defaultUserService{
		cli: cli,
	}
}

func (m *defaultUserService) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	client := userclient.NewUserServiceClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}
