// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	user "code-storm/api/internal/handler/user"
	"code-storm/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/create",
				Handler: user.CreateUserHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/id/:userId",
				Handler: user.GetUserHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/user"),
	)
}
