// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// StormUserColumns holds the columns for the "storm_user" table.
	StormUserColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "account", Type: field.TypeString, Comment: "账号"},
		{Name: "password", Type: field.TypeString, Comment: "密码"},
		{Name: "name", Type: field.TypeString, Comment: "名称"},
		{Name: "real_name", Type: field.TypeString, Comment: "真实姓名"},
		{Name: "phone", Type: field.TypeString, Comment: "电话"},
		{Name: "address", Type: field.TypeString, Comment: "电话"},
		{Name: "create_at", Type: field.TypeTime, Comment: "create time | 创建时间"},
	}
	// StormUserTable holds the schema information for the "storm_user" table.
	StormUserTable = &schema.Table{
		Name:       "storm_user",
		Columns:    StormUserColumns,
		PrimaryKey: []*schema.Column{StormUserColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		StormUserTable,
	}
)

func init() {
	StormUserTable.Annotation = &entsql.Annotation{
		Table: "storm_user",
	}
}
