// Code generated by goctl. DO NOT EDIT.
// Source: sys.proto

package userservice

import (
	"context"

	"code-storm/rpc/sys/sysClient"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddAppReq            = sysClient.AddAppReq
	AddAppResp           = sysClient.AddAppResp
	AddDepartmentReq     = sysClient.AddDepartmentReq
	AddDepartmentResp    = sysClient.AddDepartmentResp
	AddPermissionReq     = sysClient.AddPermissionReq
	AddPermissionResp    = sysClient.AddPermissionResp
	AddRoleReq           = sysClient.AddRoleReq
	AddRoleResp          = sysClient.AddRoleResp
	AppInfoReq           = sysClient.AppInfoReq
	AppInfoResp          = sysClient.AppInfoResp
	DeleteAppReq         = sysClient.DeleteAppReq
	DeleteAppResp        = sysClient.DeleteAppResp
	DeleteDepartmentReq  = sysClient.DeleteDepartmentReq
	DeleteDepartmentResp = sysClient.DeleteDepartmentResp
	DeletePermissionReq  = sysClient.DeletePermissionReq
	DeletePermissionResp = sysClient.DeletePermissionResp
	DeleteRoleReq        = sysClient.DeleteRoleReq
	DeleteRoleResp       = sysClient.DeleteRoleResp
	DepartmentInfoReq    = sysClient.DepartmentInfoReq
	DepartmentInfoResp   = sysClient.DepartmentInfoResp
	ListAppReq           = sysClient.ListAppReq
	ListAppResp          = sysClient.ListAppResp
	ListDepartmentReq    = sysClient.ListDepartmentReq
	ListDepartmentResp   = sysClient.ListDepartmentResp
	ListPermissionReq    = sysClient.ListPermissionReq
	ListPermissionResp   = sysClient.ListPermissionResp
	ListRoleReq          = sysClient.ListRoleReq
	ListRoleResp         = sysClient.ListRoleResp
	LoginReq             = sysClient.LoginReq
	LoginResp            = sysClient.LoginResp
	PermissionInfoReq    = sysClient.PermissionInfoReq
	PermissionInfoResp   = sysClient.PermissionInfoResp
	RoleInfoReq          = sysClient.RoleInfoReq
	RoleInfoResp         = sysClient.RoleInfoResp
	UpdateAppReq         = sysClient.UpdateAppReq
	UpdateAppResp        = sysClient.UpdateAppResp
	UpdateDepartmentReq  = sysClient.UpdateDepartmentReq
	UpdateDepartmentResp = sysClient.UpdateDepartmentResp
	UpdatePermissionReq  = sysClient.UpdatePermissionReq
	UpdatePermissionResp = sysClient.UpdatePermissionResp
	UpdateRoleReq        = sysClient.UpdateRoleReq
	UpdateRoleResp       = sysClient.UpdateRoleResp
	UserInfo             = sysClient.UserInfo
	UserListReq          = sysClient.UserListReq
	UserListResp         = sysClient.UserListResp

	UserService interface {
		Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
		GetUserList(ctx context.Context, in *UserListReq, opts ...grpc.CallOption) (*UserListResp, error)
	}

	defaultUserService struct {
		cli zrpc.Client
	}
)

func NewUserService(cli zrpc.Client) UserService {
	return &defaultUserService{
		cli: cli,
	}
}

func (m *defaultUserService) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	client := sysClient.NewUserServiceClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

func (m *defaultUserService) GetUserList(ctx context.Context, in *UserListReq, opts ...grpc.CallOption) (*UserListResp, error) {
	client := sysClient.NewUserServiceClient(m.cli.Conn())
	return client.GetUserList(ctx, in, opts...)
}
