// Code generated by goctl. DO NOT EDIT.
// Source: sys.proto

package server

import (
	"context"

	"code-storm/rpc/sys/internal/logic/userservice"
	"code-storm/rpc/sys/internal/svc"
	"code-storm/rpc/sys/sysClient"
)

type UserServiceServer struct {
	svcCtx *svc.ServiceContext
	sysClient.UnimplementedUserServiceServer
}

func NewUserServiceServer(svcCtx *svc.ServiceContext) *UserServiceServer {
	return &UserServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServiceServer) Login(ctx context.Context, in *sysClient.LoginReq) (*sysClient.LoginResp, error) {
	l := userservicelogic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UserServiceServer) GetUserList(ctx context.Context, in *sysClient.UserListReq) (*sysClient.UserListResp, error) {
	l := userservicelogic.NewGetUserListLogic(ctx, s.svcCtx)
	return l.GetUserList(in)
}
