// Code generated by goctl. DO NOT EDIT.
// Source: sys.proto

package appservice

import (
	"context"

	"code-storm/rpc/sys/sysClient"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddAppReq            = sysClient.AddAppReq
	AddAppResp           = sysClient.AddAppResp
	AddDepartmentReq     = sysClient.AddDepartmentReq
	AddDepartmentResp    = sysClient.AddDepartmentResp
	AddPermissionReq     = sysClient.AddPermissionReq
	AddPermissionResp    = sysClient.AddPermissionResp
	AddRoleReq           = sysClient.AddRoleReq
	AddRoleResp          = sysClient.AddRoleResp
	AppInfoReq           = sysClient.AppInfoReq
	AppInfoResp          = sysClient.AppInfoResp
	DeleteAppReq         = sysClient.DeleteAppReq
	DeleteAppResp        = sysClient.DeleteAppResp
	DeleteDepartmentReq  = sysClient.DeleteDepartmentReq
	DeleteDepartmentResp = sysClient.DeleteDepartmentResp
	DeletePermissionReq  = sysClient.DeletePermissionReq
	DeletePermissionResp = sysClient.DeletePermissionResp
	DeleteRoleReq        = sysClient.DeleteRoleReq
	DeleteRoleResp       = sysClient.DeleteRoleResp
	DepartmentInfoReq    = sysClient.DepartmentInfoReq
	DepartmentInfoResp   = sysClient.DepartmentInfoResp
	ListAppReq           = sysClient.ListAppReq
	ListAppResp          = sysClient.ListAppResp
	ListDepartmentReq    = sysClient.ListDepartmentReq
	ListDepartmentResp   = sysClient.ListDepartmentResp
	ListPermissionReq    = sysClient.ListPermissionReq
	ListPermissionResp   = sysClient.ListPermissionResp
	ListRoleReq          = sysClient.ListRoleReq
	ListRoleResp         = sysClient.ListRoleResp
	LoginReq             = sysClient.LoginReq
	LoginResp            = sysClient.LoginResp
	PermissionInfoReq    = sysClient.PermissionInfoReq
	PermissionInfoResp   = sysClient.PermissionInfoResp
	RoleInfoReq          = sysClient.RoleInfoReq
	RoleInfoResp         = sysClient.RoleInfoResp
	UpdateAppReq         = sysClient.UpdateAppReq
	UpdateAppResp        = sysClient.UpdateAppResp
	UpdateDepartmentReq  = sysClient.UpdateDepartmentReq
	UpdateDepartmentResp = sysClient.UpdateDepartmentResp
	UpdatePermissionReq  = sysClient.UpdatePermissionReq
	UpdatePermissionResp = sysClient.UpdatePermissionResp
	UpdateRoleReq        = sysClient.UpdateRoleReq
	UpdateRoleResp       = sysClient.UpdateRoleResp
	UserInfo             = sysClient.UserInfo
	UserListReq          = sysClient.UserListReq
	UserListResp         = sysClient.UserListResp

	AppService interface {
		AppAdd(ctx context.Context, in *AddAppReq, opts ...grpc.CallOption) (*AddAppResp, error)
		AppInfo(ctx context.Context, in *AppInfoReq, opts ...grpc.CallOption) (*AppInfoResp, error)
		AppList(ctx context.Context, in *ListAppReq, opts ...grpc.CallOption) (*ListAppResp, error)
		AppUpdate(ctx context.Context, in *UpdateAppReq, opts ...grpc.CallOption) (*UpdateAppResp, error)
		AppDelete(ctx context.Context, in *DeleteAppReq, opts ...grpc.CallOption) (*DeleteAppResp, error)
	}

	defaultAppService struct {
		cli zrpc.Client
	}
)

func NewAppService(cli zrpc.Client) AppService {
	return &defaultAppService{
		cli: cli,
	}
}

func (m *defaultAppService) AppAdd(ctx context.Context, in *AddAppReq, opts ...grpc.CallOption) (*AddAppResp, error) {
	client := sysClient.NewAppServiceClient(m.cli.Conn())
	return client.AppAdd(ctx, in, opts...)
}

func (m *defaultAppService) AppInfo(ctx context.Context, in *AppInfoReq, opts ...grpc.CallOption) (*AppInfoResp, error) {
	client := sysClient.NewAppServiceClient(m.cli.Conn())
	return client.AppInfo(ctx, in, opts...)
}

func (m *defaultAppService) AppList(ctx context.Context, in *ListAppReq, opts ...grpc.CallOption) (*ListAppResp, error) {
	client := sysClient.NewAppServiceClient(m.cli.Conn())
	return client.AppList(ctx, in, opts...)
}

func (m *defaultAppService) AppUpdate(ctx context.Context, in *UpdateAppReq, opts ...grpc.CallOption) (*UpdateAppResp, error) {
	client := sysClient.NewAppServiceClient(m.cli.Conn())
	return client.AppUpdate(ctx, in, opts...)
}

func (m *defaultAppService) AppDelete(ctx context.Context, in *DeleteAppReq, opts ...grpc.CallOption) (*DeleteAppResp, error) {
	client := sysClient.NewAppServiceClient(m.cli.Conn())
	return client.AppDelete(ctx, in, opts...)
}
