// Code generated by goctl. DO NOT EDIT.
// Source: sys.proto

package server

import (
	"context"

	"code-storm/rpc/sys/internal/logic/userrpc"
	"code-storm/rpc/sys/internal/svc"
	"code-storm/rpc/sys/sysClient"
)

type UserRpcServer struct {
	svcCtx *svc.ServiceContext
	sysClient.UnimplementedUserRpcServer
}

func NewUserRpcServer(svcCtx *svc.ServiceContext) *UserRpcServer {
	return &UserRpcServer{
		svcCtx: svcCtx,
	}
}

func (s *UserRpcServer) Login(ctx context.Context, in *sysClient.LoginReq) (*sysClient.LoginResp, error) {
	l := userrpclogic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UserRpcServer) GetUserList(ctx context.Context, in *sysClient.UserListReq) (*sysClient.UserListResp, error) {
	l := userrpclogic.NewGetUserListLogic(ctx, s.svcCtx)
	return l.GetUserList(in)
}
